### PR TITLE
Emit dragscrollstart, dragscrollmove, and dragscrollend events

### PR DESCRIPTION
**Pull request by celeryclub**
Fixes https://github.com/donmbelembe/vue-dragscroll/issues/6. Please let me know if there are any changes you'd like me to make. I included the build in this commit - I could also remove that if you'd prefer. Thanks!

### CODE REVIEW

**Comment by donmbelembe** [comment]
Thanks for your PR. I think it's good, I have to update docs and publish to npm

**Comment by celeryclub** [comment]
Thanks so much for the quick merge! I'll keep an eye out for that release.

**Comment by donmbelembe** [comment]
I've published it on NPM and released and new version on github. thanks for your contribution @celeryclub

**Comment by celeryclub** [comment]
Looks great! Thank you for the quick turnaround. 🍻

**Pull request merged**
