### PR TITLE
Export directive from package instead of VueDragscroll object

### PR DESCRIPTION
**Pull request by celeryclub**
Hi there. It's me again. This PR adds support for exporting the directive from the NPM package, giving people who use Webpack (like me) more flexibility in how they register the `dragscroll` directive. Currently it's not possible to register it within the scope of a component only, but this PR adds support for that. Updated the docs too this time. Let me know what you think.

Thanks very much for your time!

### CODE REVIEW

**Comment by donmbelembe** [comment]
of course it is posible to register in the scope of a component
that way

```
import { dragscroll } from 'vue-dragscroll' 
export default { directives: { dragscroll } }
```

**Comment by donmbelembe** [comment]
But you are right it gives more flexibility

**Comment by donmbelembe** [comment]
This should be a major release because previously we registered the directive using `Vue.use(VueDragscroll) ` now it will be `Vue.directive('dragscroll', dragscroll)`

**Comment by celeryclub** [comment]
Hey there. Thanks for the quick reply.
I don't think this is possible in v1.4.0:
```import { dragscroll } from 'vue-dragscroll'
export default { directives: { dragscroll } }
```
I've tried it and it doesn't seem to work. It did work in v1.3.1 but was broken in v1.4.0 - specifically this commit: https://github.com/donmbelembe/vue-dragscroll/commit/e345a4d9d4b2c186460cbdfffdcee288cb1a053a
I think the reason is that `dragscroll` is no longer exposed on the export object. Now we only have `install`.

This PR restores the functionality that was lost in v1.4.0. Technically it is still a breaking change because `import { dragscroll } from 'vue-dragscroll'` now becomes `import dragscroll from 'vue-dragscroll'`, so I understand if you want to hold off on this change till the next major release.

Thank you for your consideration!

**Comment by donmbelembe** [comment]
**v1.4.2**
I've added this line `export { directive as dragscroll }` inside [src/main.js](https://github.com/donmbelembe/vue-dragscroll/blob/master/src/main.js) to fix that problem for people who have included inside components like this:
`import { dragscroll } from 'vue-dragscroll'`
`
export default {
  name: 'MyComponent',
  directives: {
    'dragscroll': dragscroll
  },
}
`

**Comment by celeryclub** [comment]
Looks great @donmbelembe. That solution works for me and it doesn't break things for other people. Thanks so much for taking care of it! 🙌🏻

**Pull request closed without merging**
